diff -Nur -x '*.orig' -x '*~' aeolus/Makefile aeolus.new/Makefile
--- aeolus/Makefile	2010-02-28 21:03:35.081036983 +0100
+++ aeolus.new/Makefile	2010-04-13 17:55:32.850981250 +0200
@@ -14,9 +14,9 @@
 #  along with this program; if not, write to the Free Software
 #  Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 
-
-PREFIX = /usr/local
-SUFFIX := $(shell uname -m | sed -e 's/^unknown/$//' -e 's/^i.86/$//' -e 's/^x86_64/$/64/')
+DESTDIR=
+PREFIX = /usr
+#SUFFIX := $(shell uname -m | sed -e 's/^unknown/$//' -e 's/^i.86/$//' -e 's/^x86_64/$/64/')
 LIBDIR = lib$(SUFFIX)
 VERSION = 0.8.2
 DISTDIR = aeolus-$(VERSION)
@@ -64,11 +64,12 @@
 
 
 install:	aeolus aeolus_x11.so aeolus_txt.so 
-	/usr/bin/install -d $(PREFIX)/$(LIBDIR)
-	/usr/bin/install -m 755 aeolus $(PREFIX)/bin
-	/usr/bin/install -m 755 aeolus_x11.so $(PREFIX)/$(LIBDIR)
-	/usr/bin/install -m 755 aeolus_txt.so $(PREFIX)/$(LIBDIR)
-	/sbin/ldconfig $(PREFIX)/$(LIBDIR)
+	/usr/bin/install -d $(DESTDIR)$(PREFIX)/$(LIBDIR)
+	/usr/bin/install -d $(DESTDIR)$(PREFIX)/bin
+	/usr/bin/install -m 755 aeolus $(DESTDIR)$(PREFIX)/bin
+	/usr/bin/install -m 755 aeolus_x11.so $(DESTDIR)$(PREFIX)/$(LIBDIR)
+	/usr/bin/install -m 755 aeolus_txt.so $(DESTDIR)$(PREFIX)/$(LIBDIR)
+#	/sbin/ldconfig $(PREFIX)/$(LIBDIR)
 
 clean:
 	/bin/rm -f *~ *.o *.d *.a *.so aeolus
